/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CodeEditor: typeof import('./components/code-editor.vue')['default']
    ExchangeDialog: typeof import('./components/exchangeDialog.vue')['default']
    IntravenousInfusionDialog: typeof import('./pages/formulas/components/intravenous-infusion/intravenous-infusion-dialog.vue')['default']
    LatexRender: typeof import('./components/latex-render.vue')['default']
    LocaleToggler: typeof import('./components/blocks/LocaleToggler.vue')['default']
    Logo: typeof import('./components/blocks/Logo.vue')['default']
    MultipleOralDosingDialog: typeof import('./pages/formulas/components/multiple-oral-dosing/multiple-oral-dosing-dialog.vue')['default']
    MultipleOralDosingGraph: typeof import('./pages/formulas/components/multiple-oral-dosing/multiple-oral-dosing-graph.vue')['default']
    NonLinearPharmacokineticsDialog: typeof import('./pages/formulas/components/nonLinearPharmacokinetics/nonLinearPharmacokinetics-dialog.vue')['default']
    NonLinearPharmacokineticsGraph: typeof import('./pages/formulas/components/nonLinearPharmacokinetics/nonLinearPharmacokinetics-graph.vue')['default']
    OralDosingPlasmaDialog: typeof import('./pages/formulas/components/oralDosingPlasmaTimeCurve/oralDosingPlasmaDialog.vue')['default']
    RankDialog: typeof import('./components/blocks/RankDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./components/blocks/Settings.vue')['default']
    SingleIvDosingDialog: typeof import('./pages/formulas/components/single-iv-dosing/single-iv-dosing-dialog.vue')['default']
    SingleIvDosingGraph: typeof import('./pages/formulas/components/single-iv-dosing/single-iv-dosing-graph.vue')['default']
    StockChart: typeof import('./components/stock-chart.vue')['default']
    ThemeToggler: typeof import('./components/blocks/ThemeToggler.vue')['default']
    TotalRank: typeof import('./components/blocks/TotalRank.vue')['default']
  }
}
